/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DocumentVault } from "./DocumentVault";
export * as factories from "./factories";
export { DocumentVault__factory } from "./factories/DocumentVault__factory";
